### ISSUE TITLE
UnboundLocalError: local variable 'size' referenced before assignment 

### ISSUE THREAD

**Issue by NeuroWinter** [chamli/CyberCrowl#3]
![image](https://cloud.githubusercontent.com/assets/7663857/16479493/bdad93ae-3ef4-11e6-85b4-9241e7f8ea72.png)

First time trying to use this against my server, and I keep getting this error.

Windows 10, Python 2.7

**Comment by tnmch** [comment]
fixed

**Comment by NeuroWinter** [comment]
Thank you
