### ISSUE TITLE
Solving HTTP redirection 

### ISSUE THREAD

**Issue by jemacom** [chamli/CyberCrowl#6]
I noticed while trying CyberCrowl on some websites that if there's HTTP redirection it just print the new URL and doesn't continue crowling.
Here's an example comparing two websites : 

[![asciicast](https://asciinema.org/a/6xkpt75oqv3epnl6yo6b0v1dt.png)](https://asciinema.org/a/6xkpt75oqv3epnl6yo6b0v1dt)

**Comment by tnmch** [comment]
Yes  , i will try to change the url to new one in this case

**Comment by jemacom** [comment]
It's better if you add an enhancement label to the issue
